### ISSUE TITLE
make prft mandatory

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/Ingest#116]
This issue was created based on the MPEG exploration on this topic. 

consider making usage of prft per segment mandatory.

`prft` box shall be present and should correspond to the studio time whenever possible. The value there should either correspond to the acquisition time of the picture (studio time) or the item at which the frame entered the encoder.

**Comment by RufaelDev** [comment]
I think this should be optional, some reasons:
a) There is signalling for prft in the manifest aswell that can be used to signal if inband prft is used or not.
ProducerReferenceTimeElement
b) Some legacy clients and some profiles do not support inband prfrt.
c) Additional overhead on the segments. 
d) interpretation and definition of the prft (inband) is not very clear (why only flags for encoder/captured but not for 
other parts like CDN)

So due to some uncertainty around prft my preference 
would be to make it optional, as it is in CMAF which we build on.

**Comment by GuillaumeBichot** [comment]
Whet is the goal of having prft? For what usage? MPD (re)construction ? Something else (latency estimation)?

**Comment by RufaelDev** [comment]
Nov 20th 
- mpd reconstruction might be use case, but does this need to be mandatory for this
Ask more input on this 
- what does it simplify, latency measurements , full path measurement, please provide some text
- some question around duplicate prft dual capture, encoders

**Comment by nicoweilelemental** [comment]
"The producer reference time permits the DASH client to control the End-to-End Latency (EEL) or the
Encoding+Distribution Latency (EDL), and permits the service provider to provide information to the client to control this value."
https://dashif.org/docs/CR-Low-Latency-Live-r8.pdf / section 9.X.6.2.3

Inband prft is mandatory if ProducerReferenceTime@inband is set to TRUE. So there is some form of correlation between the input and the output requirements, from the packager standpoint, unless the packager ingest segments without prft and re-creates the prft in the segments from the ProducerReferenceTime vaue present in the manifest, which can be challenging as it requires the packager to keep a very precise history of the encoding sessions, as the MPD is uploaded only once. Distributed packagers don't really have such notion of encoding session, to start with.

I would therefore recommend to make prft per segment mandatory on the ingest side if the same boxes are required on the output side of the packager/origin.

**Comment by ZmGorynych** [comment]
We need prft for PCR-like functionality. In practice there can be a clock drift, and you need to detect it and adjust to it. The assumption that everything is synchronized by external means (NTP) is dangerous when we are talking about 24x7 channels, fault tolerance, and geographically distributed encoders. Remember that due to speed of light  the time at which frame X entered your encoder in London may be very different from the time the same frame made it to Denver or Tokyo. 

You may want to pass a translation of the genlock time (if you can do this) so that you can keep things in sync throughout the chain.

**Comment by ZmGorynych** [comment]
basemediadecodetime  is media time. prft is real time (i.e., wall clock time at contribution or distribution encoder). 
Same as the difference between the function of PCR and of PTS/DTS in MPEG-2 TS. We do need this functionality for long-form content as eventually any two clocks will drift relatively to each other. 
This also lets you as a packager correlate between two segments generated by different unsynchronized encoders from the same source.

**Comment by RufaelDev** [comment]
Jan 22. 
Some discussion on the two use cases: PCR and low latency are related,  in these cases it shall be mandatory.
There is a case for making overall mandatory. AP contact encoder vendors for their opinion and double check the semantics of the box. Some companies use it some not. DVB also did not adopt this, check their concerns aswell.

**Comment by acbegen** [comment]
Here is the proposed text on prft: 

20. In a CMAF presentation, all the CMAF segments that belong to at least one of the CMAF tracks MUST include a "prft" box. The "prft" box permits the end client to compute the end-to-end latency or the encoding plus distribution latency. 

I think this belongs to section 6.2 (https://dashif-documents.azurewebsites.net/Ingest/pull/143/DASH-IF-Ingest.html#interface-1-requirements). Or, since it can also be helpful for Interface-2, we can put the requirement in Section 5.

**Comment by RufaelDev** [comment]
march 12. modified proposal to be included with the text:

20. One or more CMAF media (audio and video) tracks shall carry ProducerReferenceTimeBoxes (prft) in the ingest. In this track all segment shall include a prft box.  The "prft" box permits the end client to compute the end-to-end latency or the encoding plus distribution latency.

**Comment by acbegen** [comment]
Incorporated into #143

**Comment by RufaelDev** [comment]
Note:
