### ISSUE TITLE
Please name the protocols/profiles

### ISSUE THREAD

**Issue by sandersaares** [Dash-Industry-Forum/Ingest#13]
It is completely incomprehensible to read text speaking of "profile 1" because it is not descriptive. I can never tell if it is talking about the packager or the CDN protocol. Please give them some understandable names.

**Comment by RufaelDev** [comment]
under discussion, what about DASH push, HLS push (profile 2), fmp4 push (profile 1) ? of DASH ingest/HLS ingest and fmp4 ingest ?

**Comment by wilaw** [comment]
My suggestions

Profile1: Unpackaged Ingest

Profile 2: Packaged Ingest

These describe the essential difference difference between the two profiles, which is that in profile 2 the media has already been packaged by some component.  I prefer this to "fmp4 ingest", which while true, applies to both profiles which are both still ingest fmp4 content. These names also do not restrict to just HLS or DASH and do not prohibit use of TS with profile 2.

**Comment by RufaelDev** [comment]
fmp4 is also a packaged format, so unpackaged is not correct, I also think profile 2 will be eventually be different for HLS and DASH, resulting in 3 profiles, fmp4 ingest, DASH ingest, HLS ingest

**Comment by sandersaares** [comment]
How about "Segment Ingest" and "(DASH) Program Ingest"?

**Comment by wilaw** [comment]
How about we name them as close as possible to what they are so they require the least amount of explanation:

CMAF ingest (profile 1)
HLS & DASH ingest (profile 2)

If in fact we end up with three profiles due to differences between HLs and DASH , then we could do with

CMAF ingest (profile 1)
DASH Ingest (profile 2)
HLS ingest (profile 3)
