### ISSUE TITLE
Doc Server is throwing 403

### ISSUE THREAD

**Issue by futzu** [Dash-Industry-Forum/Ingest#164]
![image](https://github.com/user-attachments/assets/d6c2d763-7025-44aa-ae37-bd84e8a26a4c)

**Comment by thasso** [comment]
Unfortunately this took a moment, but this was fixed with #165. The readme us updated and the new URLs are:

http://dashif.org/Ingest/ for the HTML version and http://dashif.org/Ingest/Ingest.pdf for the PDF. *Note* that currently we are not creating the zip file anymore.

I'm closing this but feel free to re-open if there is still an issue.

**Comment by futzu** [comment]
Thanks man.
