### ISSUE TITLE
track role for subtitles and other tracks

### ISSUE THREAD

**Issue by RufaelDev** [Dash-Industry-Forum/Ingest#40]
how to signal role of subtitle track 

proposal:

kind box is used in CMAF, provides two strings signalling the urn and the value 
use the urn:mpeg:dash:role:2011 and the values defined in DASH IOP:

- caption 
- subtitle 
- main 
- alternate 
- supplementary 
- sign 
- emergency
- forced_subtitle

otherwise when no value the role Main is assumed

add this to the subtitle section

**Comment by technogeek00** [comment]
I concur with the usage of the `kind` box for this purpose

**Comment by RufaelDev** [comment]
we need to check for HLS aswell e.g.: 
     SUBTITLES Rendition MAY include the following characteristics:
      "public.accessibility.transcribes-spoken-dialog",
      "public.accessibility.describes-music-and-sound", and
      "public.easy-to-read" (which indicates that the subtitles have
      been edited for ease of reading).

      An AUDIO Rendition MAY include the following characteristic:
      "public.accessibility.describes-video".

      The CHARACTERISTICS attribute MAY include private UTIs.

**Comment by technogeek00** [comment]
Subtitle
`public.accessibility.transcribes-spoken-dialog` => `subtitle`
`public.accessibility.describes-music-and-sound` => `caption`
`public.easy-to-read` => see amd.5
Audio
`public.accessibility.describes-video` => `description`

**Comment by KevinCJohns** [comment]
2/13 WG Call
Agreed to use the kind box to signal the role. Mappings are not normative, just suggestions. The actual mapping is a function of the environment being operated within (e.g., regulatory). Any missing roles need to be added to the role table in amendment 5 (MPEG Doc) via liaison.

**Comment by technogeek00** [comment]
Full list for `urn:mpeg:dash:role:2011` combining 3rd edition and Amd5:

| *`Role`*`@value` | Source | Description |
|------------------|--------|-------------|
| `caption` | 3rd Edition | textual media component containing transcriptions of spoken dialog and auditory cues such as sound effects and music for the hearing impaired
| `subtitle` | 3rd Edition | textual transcriptions of spoken dialog
| `main` | 3rd Edition | main media component(s) which is/are intended for presentation if no other information is provided
| `alternate` | 3rd Edition | media content component(s) that is/are an alternative to (a) main media content component(s) of the same media component type
| `supplementary` | 3rd Edition | media content component that is supplementary to a media content component of a different media component type
| `commentary` | 3rd Edition | experience that contains a commentary (e.g. director’s commentary) (typically audio)
| `dub` | 3rd Edition | experience that contains an element that is presented in a different language from the original (e.g. dubbed audio, translated captions)
| `description` | 3rd Edition | Textual or audio media component containing a textual description (intended for audio synthesis) or an audio description describing a visual component
| `sign` | 3rd Edition | Visual media component representing a sign-language interpretation of an audio component.
| `metadata` | 3rd Edition | Media component containing information intended to be processed by application specific elements.
| `enhanced-audio-intelligibility` | 3rd Edition | experience containing an element for improved intelligibility of the dialogue
| `emergency` | 3rd Edition | experience that provides information, about a current emergency, that is intended to enable the protection of life, health, safety, and property, and may also include critical details regarding the emergency and how to respond to the emergency
| `forced-subtitle` | Amd.5 | Textual information meant for display when no other text representation is selected. It is used to clarify dialogue, alternate languages, texted graphics or location/person IDs that are not otherwise covered in the dubbed/localized audio.
| `easyreader` | Amd.5 | Simplified or reduced captions as specified in [United States Code Title 47 CFR 79.103(c)(9)].
| `karaoke` | Amd.5 | Textual representation of a songs’ lyrics, usually in the same language as the associated song as specified in [SMPTE ST 2067-2].

Note the descriptions for `caption` and `subtitle` are from our internal understanding, they are not specified within MPEG-DASH (though perhaps should be)

Based on these we at least have full coverage of the HLS characteristics and at least can provide DASH role as a non-normative suggestion.

| Characteristic | Role |
|----|----|
|`public.accessibility.transcribes-spoken-dialog` | `subtitle` |
|`public.accessibility.describes-music-and-sound` | `caption` |
|`public.easy-to-read` | `easyreader` |
|`public.accessibility.describes-video` | `description` |

**Comment by boy-vd** [comment]
Hi, I'm a colleague of @RufaelDev at Unified Streaming and would like to provide some additional input.

1. It might be worthwhile to add that when the `forced-subtitle` DASH role is present, this may be mapped to HLS's `FORCED=YES` in the `#EXT-X-MEDIA` info of a subtitles track.

2. In addition to suggestions for mapping DASH roles to specifics in the HLS output, I may be useful to create something similar for DVB-DASH output.

Regarding the mapping for DVB-DASH, this is what ETSI TS 103 285 specifies for the output of accessibility features (with the `urn:tva:metadata:cs:AudioPurposeCS:2007` scheme being defined in the TV-Anytime specification (ETSI TS 102 822-3-1)):

Description                       | Media type | Role element                | Accessibility element
--------------------------------- | ---------- | --------------------------- | ----------------------------------------------------------
Audio description (broadcast mix) | Audio      | `alternate`                   | `@schemeIdUri="urn:tva:metadata:cs:AudioPurposeCS:2007@1"`
Audio description (receiver mix)  | Audio      | `commentary`                  | `@schemeIdUri="urn:tva:metadata:cs:AudioPurposeCS:2007@1"`
Clean Audio                       | Audio      | `alternate`                   | `@schemeIdUri="urn:tva:metadata:cs:AudioPurposeCS:2007@2"`
Captions                          | Text       | `main`                        | `@schemeIdUri="urn:tva:metadata:cs:AudioPurposeCS:2007@2"`

This is problematic, because it cannot be catered to without creating some problematic edge cases for regular DASH output. For example: if 'Audio description (recevier mix)' track would be signaled in the ingest according to the DVB-DASH specification, it would be interpreted as a `commentary` track for regular DASH ouptut (given the presence of the `commentary` DASH role).

My suggestion:

 Media type | DASH role ingest               | Signaling for DVB-DASH output
 ---------- | ------------------------------ | ----------------------------------------------------------
 Audio      | `description`                    | Audio description (broadcast mix)
 Audio      | `description` + `supplementary`  | Audio description (receiver mix) 
 Audio      | `enhanced-audio-intelligibility` | Clean Audio           
 Text       | `caption`                        | Captions    

Instead of the need for two DASH roles to get the signaling for 'Audio description (receiver mix)' for DVB-DASH output, it would perhaps also be an optoin to create a specific DASH role for the 'Audio description (receiver mix)' use case.

3. The HLS mapping as suggested by @technogeek00 looks good to me (although I personally think that the need for `public.accessibility.transcribes-spoken-dialog` is rather ambiguous, because it is not mentioned in Apple's authoring guidelines and if taken at face value it should also be present for a `caption` track, which transcribes spoken dialog _and_ describes music and sound, but that is more of an issue with HLS itself than with the suggested mapping).

**Comment by boy-vd** [comment]
I noticed I left out part of the DVB-DASH signaling for subtitle tracks. Here is a complete overview, of which my earlier comment only mentioned the first:

Description                                                                                             | Language                             | Role element in MPD | Accessibility element in MPD
------------------------------------------------------------------------------------------------------- | ------------------------------------ | ------------ | ----------------------------------------------------------
Subtitles for the hard of hearing in the same language as the programme                                 | Same as main audio for the programme | `main`         | `@schemeIdUri="urn:tva:metadata:cs:AudioPurposeCS:2007@2"`
Subtitles providing a translation of the main audio of the programme                                    | Language of subtitles                | `alternate`    |
Subtitles providing additional information for the programme                                            | Language of subtitles                | `commentary`   |
Programme uses subtitles to translate foreign soundtrack or parts of soundtrack into preferred language | Language of subtitles                | `main`         | 

Based on this information, the mapping for text track could look like this:

Media type | DASH role ingest           | Role element in MPD | Accessibility element in MPD
---------- | -------------------------- | ------------ | ----------------------------------------------------------
Text       | `caption`                  | `main`         | `@schemeIdUri="urn:tva:metadata:cs:AudioPurposeCS:2007@2"`
Text       | `subtitle`                 | `alternate`    |
Text       | `commentary`               | `commentary`   |
Text       | `forced-subtitle` or `dub` | `main`         |

**Comment by RufaelDev** [comment]
thanks for the inputs, we can add an informative table about this possible mapping between DASH and HLS which seems complete enough, DVB-DASH roles can be explicitly signalled by having the accesibility element and role element in a kind box, similar as other protocol specific defined   roles

**Comment by technogeek00** [comment]
@samcurran22 I believe the only mandatory signaling is if you are following the DASH-IF IOP profile and have multiple `AdaptationSet` elements for one media type you should have a `Role` element describing which adaptation set is `"main"`.

Generally though roles are just useful in consistently describing the purpose of renditions without having to interpret id values in a specific way or provide custom xml extensions.
