### ISSUE TITLE
Generic ID3 metadata ingest

### ISSUE THREAD

**Issue by johndeu** [Dash-Industry-Forum/Ingest#44]
Not sure if this is really an issue on our spec or more of an industry question.  I noticed that we are defining a few schemeID URIs in the spec for 'emsg', and we have an example that shows "Nielsen" specific ID3. 
Should we also provide a proper URN for generic ID3 metadata?  Is there an official ID3 scheme URN we should use?

**Comment by johndeu** [comment]
For example, could we add a valid URN like:
urn:id3:2.4:bin  to map to  http://id3.org/id3v2.4.0-structure 

And it would be base64 encoded into the 'emsg' message_data.

**Comment by RufaelDev** [comment]
Hi John,  as id3 is not really a standard it may make sense to define the urn in the ingest specification, I even we can define a more comprehensive list of metadata urn in the ingest spec,

**Comment by johndeu** [comment]
Agreed.  I made a mistake above. Does not need to be base64 in the message_data. That can be binary... meant the output in the manifest <Event> in the <EventStream> if provided would need to be base64

It would be great to come up with a list of the most common timed metadata formats that could be used in emsg on ingest and provide that list so that any Profile 1 server would know to process those in band messages and pass them through, and it could be part of the conformance testing.

**Comment by RufaelDev** [comment]
The mpd event in eventstream can since amendment 5 be explicitly represented as base64 via the content encoding attribute in the eventtype, for the binary inband emsg indeed base64 is not needed. This means that since amdmnt 5 conversion between inband emsg or metadata track to mpd event and vice versa is well defined and not depending on the uri scheme.

 Just one note, the timed metadata track need not necessarily embed emsg, it is also possible to directly write id3 or binary scte-35 as sparse samples by signalling the urn in URIMetasampleEntry, but embedding in additional emsg is possible creating another layer of encapsulation ,  if we want to standardize and have conformance around this we should think if we want this additional layer of encapsulation or not and if both options should be allowed or not. Right now both options are allowed

**Comment by RufaelDev** [comment]
Add the carriage of id3 tags timed metadata as defined in https://aomediacodec.github.io/av1-id3/

**Comment by RufaelDev** [comment]
added the reference to id3 carriage in the specification
