### ISSUE TITLE
Change "Profile" naming to 'Interface"

### ISSUE THREAD

**Issue by wilaw** [Dash-Industry-Forum/Ingest#45]
Based on Discussion within DASH IF live TF, it has been pointed out that the two publishing modes do not meet the general industry of a profile, in which the bulk of implementation is common and one is typically a restriction of the other. A preferred term would be "Interface".

**Comment by RufaelDev** [comment]
Just some arguments for using profiles as decided from early on by the group. As both profiles use CMAF as underlying format and the procedures for establishing connection and some of the failover procedures are similar, the two interface were defined as profiles:
- POST with chunked transfer encoding 
- correctly formatted CMAF Headers and Fragments 
- handling of failures (to some extend)
- DNS resolution 
- security/authentication
 - naming of tracks
are all similar, so bulk of operation is similar, 
I agree the profiles can be used to implement two different interfaces as defined in Live TF (IF-1,IF-2)
e.g. ingest to packager, ingest to CDN origin, but from the beginning of the work it was chosen to keep the two aligned as much as possible via profiles, to make things easier for implementers (for example, instead of a pure CMAF ingest a manifest is added enabling DASH or HLS ingest). Also, I think it is only a benefit that the profiles can be used to implement different interfaces in live TF, also I consider the ingest spec work relevant for other architectures that can be considered cross the industry, and address key use cases there.

I am ok with changing some of the naming in the document or referring to the fact that profiles can implement different interfaces, and the differences between the two are mentioned explicitly in the text, but I also don't see the reason to exagerate the differences between the two profiles while the bulk of operation is quite similar. This is by no means incidental, as  we started this work based on a common media format CMAF and HTTP POST trying to avoid industry fragmentation. I think we should make a best effort to stick to that approach.

**Comment by RufaelDev** [comment]
updated profile to interface in latest version
