### ISSUE TITLE
Requirements for Live Media Source Failover

### ISSUE THREAD

**Issue by KevinCJohns** [Dash-Industry-Forum/Ingest#57]
In addition to the requirements covered in this section, we may want to consider the use case covered in the beginning of the document (diagram 5 workflow with redundant Ingest sources and receiving entities).  It seems there would need to be some requirements on the Media Processing Entity to be prepared to receive duplicate content and treat accordingly? We would also need to provide guidance on how the MPE should handle duplicate posts but the content does not match (e.g., not time sync'ed). Presumably it wants to prefer one over the other for consistency?

**Comment by RufaelDev** [comment]
This can go to implementation guidelines and best practices, the way the receiver handles the content that does not involve communicating back to the ingest source is not in scope of the spec. Yet it is important to document this behavior in the implementation guidelines.

**Comment by RufaelDev** [comment]
leave open until next call (18th of sept), await feedback

**Comment by johndeu** [comment]
@RufaelDev  - I'll ask Sam to review this

**Comment by samgzhang** [comment]
Agree that it would be great to add a section to describe guidelines and best practices for solutions with redundancy (encoder or MPE). Section 5.1 is mostly talking about synchronization requirements for a single MPE within the same switching set.

**Comment by RufaelDev** [comment]
@acbegen this was what was discussed in the f2f meeting in San Diego last year, indeed right now the spec cannot support multiple encoders that are not in sync. According to some of the large encoder vendors achieving synchronization was manageable using for example the timestamps in the SDI sources. Note that this is purely about identical fmp4 timestamps mapping to identical video frames (bitstreams need not be identical), fragments may arrive out of sync at the ingest source, that is ok.  I am not sure how this would be fixed otherwise, as with so many things it is best to fix problems as early as possible. How can a receiver fix incorrect encoder input later on ? Unless there is an answer to this, I don't think the specification can solve this even in a later stage.

**Comment by RufaelDev** [comment]
@samgzhang this was supposed to be section 5.7 https://dashif-documents.azurewebsites.net/Ingest/master/DASH-IF-Ingest.html#failover
