### ISSUE TITLE
Comments on 5.4)

### ISSUE THREAD

**Issue by haudiobe** [Dash-Industry-Forum/Ingest#96]
https://dashif-documents.azurewebsites.net/Ingest/master/DASH-IF-Ingest.html#Requirements_for_switchingsets

1) Change switchingsets to Switching Sets and adaptationsets to Adaptation Sets
2) Please remove Table 2. It is a copy and paste and unnecessary.
3) What does "Aligned swtiching sets may also be signalled" mean? Fix also typo
4) On "For additional signalling of CMAF tracks belonging to the same switching set, the ingest source MAY set the alternate_group value in the TrackHeaderBox tkhd to a value that is the same for tracks belonging to the same switching set. This allows explicit signalling of tracks that do apply to switchingset constraints but do not belong to the same switching set. Alternatively, this may enable easy identification of a switchingset. " This is not correct. One cannot use alternate_group value for such signaling. If we make this a rule then we must add this here in the spec as a requirement. 
5) "Alternatively one could signal switching explicitly by means outside of this specification." Please refer to the DASH profile for CMAF content in WD of Amd.1

**Comment by samgzhang** [comment]
Regarding #4, is there a recommendation on what box/field that could be used for this purpose? I think the need of being able to explicitly signal switching set is definitely there and ideally it can be done by using an existing MP4 box/field that can be tied to a track.

**Comment by RufaelDev** [comment]
We see some disadvantage in signalling this in the track itself, as a track could for example be used in different presentations/switching sets later on (late binding), also, this feature of explicit signalling is not supported in CMAF. To enable this feature in this specification, how about adding a switching set identified 

e.g. POST chunk.cmfv pub_point_URI/Switching(ss_id)/Streams(stream_1)

or

POST chunk.cmfv pub_point_URI/Streams(stream_1)/Switching(ss_id)/

were ss_id is a unique identifier for that live streaming session (event).
An encoder can generate this, it is only unique for the pub_point/channel at that time 

In interface 2 this may be used as 
POST chunk10.cmfv pub_point_URI/Switching(ss_id)/Streams(stream_1)/chunkX.cmfv 
when files will be neatly organized in the structure of the switching sets and streams. 

I propose this solution as changing things in CMAF tracks will be tricky at this stage, and 
the problem seems very particular to CMAF ingest without a manifest, while in many cases 
a manifest is assumed.

Would this be a feasible solution ? I would like to have this issue resolved as it has been standing for a while.

**Comment by RufaelDev** [comment]
TF 2nd october 2019, agreed to have these two additional signalling close the issue
